### ISSUE TITLE
should the exception be caught in deserialize?

### ISSUE THREAD

**Issue by ShaneJIan** [advanced-stack/py-llm-core#14]
BaseParser.java 
def deserialize(self, json_str):
    try:
        attributes = dirtyjson.loads(json_str)
        return from_dict(self.target_cls, attributes)
    except dirtyjson.error.Error as e:
        print(f"Failed to parse JSON string: {e}")
        # handle the error appropriately, perhaps returning None or a default value
        return None

**Comment by paschembri** [comment]
I thought of raising a custom exception when the result is not valid JSON.

I don't think we should return None or a default value because the goal is to actually create an instance of target_cls. 

If the data is not a JSON string, our only choice is to fail and let the upstream application deal with that case (retry, change the context window, ...)

Does a custom exception make sense, something like `InvalidLLMJSONResponse` ?

**Comment by paschembri** [comment]
The `parse` method now (v3) catches the exception when unable to deserialize and prints the erroneous string (but still re-raise the exception)
